# file: base/configuration.yaml

varReference:
# Gloo Related
- path: spec/ssl_config/sniDomains
  kind: VirtualService
  apiVersion: gateway.solo.io/v1
- path: spec/ssl_config/secret_ref/name
  kind: VirtualService
  apiVersion: gateway.solo.io/v1
- path: spec/ssl_config/secret_ref/namespace
  kind: VirtualService
  apiVersion: gateway.solo.io/v1
- path: spec/virtualHost/domains
  kind: VirtualService
  apiVersion: gateway.solo.io/v1
- path: spec/virtualHost/routes/redirectAction/hostRedirect
  kind: VirtualService
  apiVersion: gateway.solo.io/v1
- path: /spec/virtualHost/routes/routeAction/single/upstream/name
  kind: VirtualService
  apiVersion: gateway.solo.io/v1
- path: metadata/name
  kind: VirtualService
  apiVersion: gateway.solo.io/v1
# Certificate Related
- path: metadata/name
  kind: Certificate
  apiVersion: gateway.solo.io/v1
- path: metadata/namespace
  kind: Certificate
  apiVersion: gateway.solo.io/v1
- path: spec/dnsNames
  kind: Certificate
  apiVersion: gateway.solo.io/v1
- path: spec/secretName
  kind: Certificate
  apiVersion: gateway.solo.io/v1
# ClusterIssuer Related
- path: spec/acme/solvers/dns01/route53/accessKeyID
  kind: ClusterIssuer
  apiVersion: cert-manager.io/v1alpha2
- path: spec/acme/solvers/dns01/route53/region
  kind: ClusterIssuer
  apiVersion: cert-manager.io/v1alpha2

