apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"helm-operator","namespace":"flux"},"spec":{"replicas":1,"selector":{"matchLabels":{"name":"helm-operator"}},"strategy":{"type":"Recreate"},"template":{"metadata":{"annotations":{"prometheus.io/scrape":"true"},"labels":{"name":"helm-operator"}},"spec":{"containers":[{"args":["--enabled-helm-versions=v3"],"image":"docker.io/fluxcd/helm-operator:1.2.0","imagePullPolicy":"IfNotPresent","livenessProbe":{"httpGet":{"path":"/healthz","port":3030},"initialDelaySeconds":1,"timeoutSeconds":5},"name":"helm-operator","ports":[{"containerPort":3030,"name":"http"}],"readinessProbe":{"httpGet":{"path":"/healthz","port":3030},"initialDelaySeconds":1,"timeoutSeconds":5},"resources":{"requests":{"cpu":"50m","memory":"64Mi"}},"volumeMounts":null}],"serviceAccountName":"helm-operator","volumes":null}}}}
  creationTimestamp: "2021-01-16T13:17:50Z"
  generation: 1
  name: helm-operator
  namespace: flux
  resourceVersion: "17082492"
  selfLink: /apis/apps/v1/namespaces/flux/deployments/helm-operator
  uid: a0870224-3a68-4b55-b0ad-998f9b24a036
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: helm-operator
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        name: helm-operator
    spec:
      containers:
      - args:
        - --enabled-helm-versions=v3
        image: docker.io/fluxcd/helm-operator:1.2.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 3030
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: helm-operator
        ports:
        - containerPort: 3030
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 3030
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: helm-operator
      serviceAccountName: helm-operator
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-01-16T13:18:01Z"
    lastUpdateTime: "2021-01-16T13:18:01Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-01-16T13:17:50Z"
    lastUpdateTime: "2021-01-16T13:18:01Z"
    message: ReplicaSet "helm-operator-6cc75fd5d8" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
