apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cluster
- flux
# - helm-operators
- cert-manager
# Patch all helm release with to `spec.helmVersion: v3`
patches:
- path: helm-version-v3.yaml
  target:
    kind: HelmRelease
