apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/cert-manager

patchesStrategicMerge:
  - cert-manager-values.yaml

configMapGenerator:
- name: service-properties
  namespace: default
  envs: [.cluster.properties]

vars:
- name: AWS_REGION
  objref: { kind: ConfigMap, name: service-properties, apiVersion: v1 }
  fieldref: { fieldpath: data.AWS_REGION }
